services:
  app:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ../.env
    depends_on:
      db: 
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/your-database

  db:
    image: postgres:13-alpine
    volumes:
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=your-database
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s  